name: CI Pipeline

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-dev && poetry run pip install pylint
      - name: Run pylint
        run: poetry run pylint batteryprobe utils/merge_tables.py 
